bugfix: ZENKO-3547 bump zenko-operator version to 1.0.0-rc.4
scality/Zenko pull request #1236
Opened 2021-05-28 23:40 UTC by terrydervaux

to satisfy web browser https security policy on zenko-ui/shell-ui

**What does this PR do, and why do we need it?**

**Which issue does this PR fix?**

fixes [ZENKO-3547](https://scality.atlassian.net/browse/ZENKO-3547)

**Special notes for your reviewers**:

2021-05-28 23:40 UTC, bert-e commented
# Hello terrydervaux,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/zenko/bert-e/doc/user).





*Status report is not available.*

2021-05-28 23:40 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZENKO-3547 contains:


* `2.0.0-rc.3`



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `2.0.0`


Please check the `Fix Version/s` of ZENKO-3547, or the target
branch of this pull request.

2021-05-28 23:42 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2021-05-28 23:50 UTC, naren-scality approved these changes

2021-05-28 23:53 UTC, RachedBenMustapha requested changes
eve has a reference to the operator version

2021-05-28 23:54 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers






The following reviewers are expecting changes from the author, or must review again:

* @rachedbenmustapha

2021-05-28 23:59 UTC, RachedBenMustapha approved these changes

2021-05-28 23:59 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2021-05-29 00:40 UTC, terrydervaux commented
/approve

2021-05-29 00:40 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/2.0`



The following branches will **NOT** be impacted:

* `development/0.9`
* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2021-05-29 00:40 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/2.0`



The following branches have **NOT** changed:

* `development/0.9`
* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`



Please check the status of the associated issue ZENKO-3547.

Goodbye terrydervaux.

2021-05-29 00:40 UTC, merged