Upgrade Cruise Control to 2.5.80
scality/Zenko pull request #1447
Opened 2022-01-05 22:39 UTC by alexanderchan-scality

fixes issues:
* CVE-2021-44832
* CVE-2021-45105

**What does this PR do, and why do we need it?**

**Which issue does this PR fix?**

fixes #<ISSUE>

**Special notes for your reviewers**:

2022-01-05 22:39 UTC, bert-e commented
# Hello alexanderchan-scality,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/zenko/bert-e/doc/user).





*Status report is not available.*

2022-01-05 22:39 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/2.2/improvement/ZENKO-3820/upgradeCruiseControl-2.5.80` with contents from `improvement/ZENKO-3820/upgradeCruiseControl-2.5.80`
and `development/2.2`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/2.2/improvement/ZENKO-3820/upgradeCruiseControl-2.5.80 origin/development/2.2
 $ git merge origin/improvement/ZENKO-3820/upgradeCruiseControl-2.5.80
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/2.2/improvement/ZENKO-3820/upgradeCruiseControl-2.5.80
```

2022-01-05 22:40 UTC, naren-rajendran approved these changes

2022-01-05 22:41 UTC, rahulreddy approved these changes

2022-01-05 22:42 UTC, rahulreddy requested changes
Can you also bump the VERSION file?

2022-01-05 22:58 UTC, RachedBenMustapha reviewed
CVE-2021-44832 was already fixed priori to this PR

2022-01-06 00:07 UTC, rahulreddy approved these changes

2022-01-06 01:01 UTC, miniscruff approved these changes

2022-01-06 01:07 UTC, alexanderchan-scality commented
/approve

2022-01-06 01:07 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/ZENKO-3820/upgradeCruiseControl-2.5.80` into
`development/2.1`
* [w/2.2/improvement/ZENKO-3820/upgradeCruiseControl-2.5.80](https://github.com/scality/zenko/compare/development/2.2...w/2.2/improvement/ZENKO-3820/upgradeCruiseControl-2.5.80) will be merged into `development/2.2` (pull request #1448)



The following branches will **NOT** be impacted:

* `development/0.9`
* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.







*The following options are set:* **approve**

2022-01-06 01:49 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/2.1`

* :heavy_check_mark: `development/2.2`



The following branches will **NOT** be impacted:

* `development/0.9`
* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2022-01-06 01:49 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/2.1`

* :heavy_check_mark: `development/2.2`



The following branches have **NOT** changed:

* `development/0.9`
* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`



Please check the status of the associated issue ZENKO-3820.

Goodbye alexanderchan-scality.

2022-01-06 01:49 UTC, merged