ZENKO-3802  Update backbeat 8.3.3
scality/Zenko pull request #1450
Opened 2022-01-08 00:02 UTC by nicolas2bert

Should fail until Zenko-operator is updated with https://github.com/scality/zenko-operator/pull/235

2022-01-08 00:02 UTC, bert-e commented
# Hello nicolas2bert,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/zenko/bert-e/doc/user).





*Status report is not available.*

2022-01-08 00:02 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZENKO-3802 contains:


* *None*



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `2.2.6`


Please check the `Fix Version/s` of ZENKO-3802, or the target
branch of this pull request.

2022-01-08 00:03 UTC, nicolas2bert commented
ping

2022-01-08 00:03 UTC, miniscruff approved these changes

2022-01-08 00:03 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2022-01-10 15:14 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZENKO-3802 contains:


* `2.2.6`



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `2.2.7`


Please check the `Fix Version/s` of ZENKO-3802, or the target
branch of this pull request.

2022-01-10 15:38 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2022-01-11 14:16 UTC, williamlardier approved these changes

2022-01-11 14:19 UTC, francoisferrand requested changes
the "other" zenkoversions.yaml (in eve/...) should be updated to match.

2022-01-11 14:19 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers






The following reviewers are expecting changes from the author, or must review again:

* @francoisferrand

2022-01-11 15:22 UTC, francoisferrand approved these changes

2022-01-11 15:22 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2022-01-11 17:36 UTC, nicolas2bert commented
@bert-e approve

2022-01-11 17:36 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/2.2`



The following branches will **NOT** be impacted:

* `development/0.9`
* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.1`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2022-01-11 18:25 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/2.2`



The following branches have **NOT** changed:

* `development/0.9`
* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.1`



Please check the status of the associated issue ZENKO-3802.

Goodbye nicolas2bert.

2022-01-11 18:25 UTC, merged