improvement: ZENKO-4043 bump cloudserver and vault
scality/Zenko pull request #1545
Opened 2022-03-21 16:33 UTC by XinLiScality

the issue is described in this ticket https://scality.atlassian.net/browse/ARTESCA-2237
post fix arsenal,  cloudserver and vault

2022-03-21 16:33 UTC, bert-e commented
# Hello xinliscality,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/zenko/bert-e/doc/user).





*Status report is not available.*

2022-03-21 16:33 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2022-03-23 15:55 UTC, francoisferrand requested changes

2022-03-23 15:55 UTC, francoisferrand commented on solution/deps.yaml
> +  tag: 8.4.4
if you bump cloudserver to 8.4.4 (and get slow listing), you must bump backbeat as well so it supports the format (v1) of newly created buckets .

backbeat should be at least 8.3.9.

2022-03-23 16:03 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers






The following reviewers are expecting changes from the author, or must review again:

* @francoisferrand

2022-03-23 16:35 UTC, XinLi0207 commented on solution/deps.yaml
> +  tag: 8.4.4
thanks, will do!

2022-03-25 09:55 UTC, closed without merging

2022-03-25 09:56 UTC, XinLiScality commented
closed cause the clouserver version will be updated in other PR