Feature/zenko-4694: bump zenko ui to 2.1.7
scality/Zenko pull request #1976
Opened 2023-11-14 12:40 UTC by JBWatenbergScality

**What does this PR do, and why do we need it?**

**Which issue does this PR fix?**

fixes #<ISSUE>

**Special notes for your reviewers**:

2023-11-14 12:40 UTC, bert-e commented
# Hello jbwatenbergscality,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://bert-e.scality.net/scality/zenko/doc/user).





*Status report is not available.*

2023-11-14 12:40 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZENKO-4694 contains:


* *None*



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `2.8.14`


Please check the `Fix Version/s` of ZENKO-4694, or the target
branch of this pull request.

2023-11-14 12:43 UTC, JBWatenbergScality commented
/approve

2023-11-14 12:43 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers











*The following options are set:* **approve**

2023-11-14 12:45 UTC, MonPote approved these changes

2023-11-14 12:46 UTC, hervedombya approved these changes

2023-11-14 14:02 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/Zenko/commit/d92d68a438f4d0e30016882a43daa7456a834130) did not succeed in branch feature/ZENKO-4694.




*The following options are set:* **approve**

2023-12-11 11:29 UTC, francoisferrand requested changes
Please wait, 2.8.14 is already in progress

2023-12-11 11:29 UTC, bert-e commented
# Conflict




There is a conflict between your branch `feature/ZENKO-4694` and the
destination branch `development/2.8`.

Please resolve the conflict on **the feature branch** (`feature/ZENKO-4694`).

```sh
git fetch && \
git checkout origin/feature/ZENKO-4694 && \
git merge origin/development/2.8
```

Resolve merge conflicts and commit

```sh
git push origin HEAD:feature/ZENKO-4694
```







*The following options are set:* **approve**

2023-12-11 13:47 UTC, closed without merging