bf: ZENKO-916 modify ACL replication test case
scality/Zenko pull request #252
Opened 2018-08-07 00:01 UTC by jonathan-gramain

Instead of waiting for replication and expecting no change, expect the
replication status to stay COMPLETED. This because we don't want ACLs
to trigger a replication at all as it would break transient source by
reading the data from the local source which has been deleted already.

2018-08-07 00:01 UTC, bert-e commented
# Hello jonathan-gramain,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get
information on this process.





*Status report is not available.*

2018-08-07 00:01 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:



* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @ssalaues

* @vrancurel

* @giacomoguiulfo

* @NicolasT

2018-08-07 00:01 UTC, jonathan-gramain commented
@bert-e wait

2018-08-07 00:21 UTC, ssalaues approved these changes

2018-08-09 20:42 UTC, dora-korpar approved these changes

2018-08-09 20:42 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/0.9`




There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of Release Engineering will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of Release Engineering now.

2018-08-09 20:42 UTC, tmacro approved these changes

2018-08-09 20:50 UTC, giacomoguiulfo commented
@bert-e wait

2018-08-09 20:53 UTC, giacope requested changes
Changes to update a docker image tag should be on a separate commit, and the commit message should contain the entire changelog of that release (and the image should be created with the proper script to update the wiki and generate the changelog). Also, whenever Cloudserver is updated, it is preferred that s3-data image tag is updated too (in the same commit).

2018-08-09 21:16 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/0.9`




Please check the status of the associated issue ZENKO-916.

Goodbye jonathan-gramain.

2018-08-09 21:17 UTC, merged