github: add pull request template
scality/Zenko pull request #271
Opened 2018-08-15 21:22 UTC by giacomoguiulfo

**What does this PR do, and why do we need it?**

So that we get "this" information on every PR.

**Which issue does this PR fix?**

None.

**Special notes for the reviewers**:

This is an example of how the Pull Request template will look like.

2018-08-15 21:22 UTC, bert-e commented
# Hello giacomoguiulfo,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get
information on this process.





*Status report is not available.*

2018-08-15 21:22 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:



* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @ssalaues

* @vrancurel

* @giacomoguiulfo

* @NicolasT

2018-08-31 18:42 UTC, tmacro approved these changes

2018-08-31 18:42 UTC, bert-e commented
# Branches have diverged



This pull request's source branch `improvement/pull-request-template` has diverged from
`development/0.9` by more than 50 commits.

To avoid any integration risks, please re-synchronize them using one of the
following solutions:

* Merge `origin/development/0.9` into `improvement/pull-request-template`
* Rebase `improvement/pull-request-template` onto `origin/development/0.9`

Note: If you choose to rebase, you may have to ask me to rebuild
integration branches using the `reset` command.

2018-08-31 19:02 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:



* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @ssalaues

* @vrancurel

* @giacomoguiulfo

* @NicolasT

2018-08-31 19:14 UTC, wabernatScality commented on .github/PULL_REQUEST_TEMPLATE.md
> +Please fill the information below if applicable.
Please enter applicable information below.

2018-08-31 19:15 UTC, wabernatScality commented on .github/PULL_REQUEST_TEMPLATE.md
> +**What this PR does and why do we need it**:
What does this PR do, and why do we need it?

2018-08-31 19:15 UTC, wabernatScality commented on .github/PULL_REQUEST_TEMPLATE.md
> +**Which issue this PR fixes**:
Which issue does this PR fix?

2018-08-31 19:15 UTC, anurag4DSB requested changes
Great Idea
I was looking at the S3 pull request template.
It would be great to add things from this too:
https://github.com/scality/cloudserver/blob/a65eb808734c056f959f09e72c3cf48414a52f6b/.github/PULL_REQUEST_TEMPLATE.md

Reason: It has scality guidelines too.

2018-08-31 19:16 UTC, anurag4DSB commented
at least have scality Contribution guidelines link: In order to contribute to the project, you must sign your work https://github.com/scality/Guidelines/blob/master/CONTRIBUTING.md#sign-your-work

2018-08-31 20:25 UTC, giacope commented
@anurag4DSB IMHO, the Cloudserver template doesn't look like a "template" and it's more like a summary of guidelines. Also, most of the guidelines are outdated and irrelevant in the context of Zenko, so I think it's pointless to reference them.
Finally, I think it will be hypocritical to ask people to sign commits under the DCO when none of us does it. If it wants to be enforced, then it should be enforced and not just mentioned. This can be done through a GitHub bot.

2018-09-04 21:31 UTC, ssalaues approved these changes

2018-09-04 21:31 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/0.9`




There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of Release Engineering will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of Release Engineering now.

2018-09-04 22:58 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/0.9`




Please check the status of the associated issue None.

Goodbye giacomoguiulfo.

2018-09-04 22:58 UTC, merged