improvement: create bootstrap lists from global or replica count
scality/Zenko pull request #308
Opened 2018-08-29 00:09 UTC by ssalaues

Allows for the backbeat chart and cloudserver chart to create bootstrap lists of all statefulsets based off global `nodeCount` or `replica` count if custom configuration is needed but default to the global `nodeCount`

2018-08-29 00:09 UTC, bert-e commented
# Hello ssalaues,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get
information on this process.





*Status report is not available.*

2018-08-29 00:10 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:



* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @ssalaues

* @vrancurel

* @giacomoguiulfo

* @NicolasT

2018-08-29 23:02 UTC, jonathan-gramain commented on kubernetes/zenko/charts/backbeat/templates/_helpers.tpl
> +{{- define "backbeat.queue" -}}
What about `backbeat.queue-hosts`, `backbeat.quorum-hosts` to precise things?

2018-09-04 20:14 UTC, giacomoguiulfo commented on kubernetes/zenko/charts/backbeat/values.yaml
> +  replicas:
Shouldn't this have a default value?

2018-09-07 19:37 UTC, giacope requested changes
Needs chart version bump

2018-09-17 16:52 UTC, bert-e commented
# Conflict




There is a conflict between your branch `improvement/ZENKO-1084-bootstrap-lists` and the
destination branch `development/1.0`.

Please resolve the conflict on **the feature branch** (`improvement/ZENKO-1084-bootstrap-lists`).

```bash
 $ git fetch
 $ git checkout origin/improvement/ZENKO-1084-bootstrap-lists
 $ git merge origin/development/1.0
 $ # <intense conflict resolution>
 $ git commit
 $ git push origin HEAD:improvement/ZENKO-1084-bootstrap-lists
```

2018-09-19 22:41 UTC, ssalaues commented
Closing this PR. A better solution would be to modify the entry point scripts of the services that require bootstrap lists.

2018-09-19 22:41 UTC, closed without merging