ZENKO 1187 sizing defaults
scality/Zenko pull request #348
Opened 2018-09-21 18:48 UTC by ssalaues

**What does this PR do, and why do we need it?**
Updates sizing defaults for 1.0 to more reasonable values that total to a 200GB per node minimum.
**Which issue does this PR fix?**

fixes ZENKO-1187

**Special notes for your reviewers**:
This breaks any upgrades to Zenko from previous versions. (Upgrades would require modifying the values.yaml to previous settings). It's best to do this prior to any production install as it will give us more peace of mind even on `default` installs where a user may not diligently update the storage values to production ready settings.

2018-09-21 18:48 UTC, bert-e commented
# Hello ssalaues,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get
information on this process.





*Status report is not available.*

2018-09-21 18:49 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:



* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @NicolasT

* @giacomoguiulfo

* @vrancurel

* @ssalaues

2018-09-21 23:48 UTC, giacope requested changes
single node values?

2018-09-22 00:04 UTC, giacope approved these changes

2018-09-22 00:05 UTC, giacomoguiulfo commented
/lgtm

2018-09-22 00:09 UTC, anurag4DSB approved these changes

2018-09-22 00:11 UTC, alexanderchan-scality approved these changes

2018-09-22 00:26 UTC, rahulreddy approved these changes

2018-09-22 00:58 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/1.0`



The following branches will **NOT** be impacted:

* `development/0.9`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of Release Engineering will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of Release Engineering now.

2018-09-22 00:58 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/1.0`



The following branches have **NOT** changed:

* `development/0.9`



Please check the status of the associated issue ZENKO-1187.

Goodbye ssalaues.

2018-09-22 00:58 UTC, merged