documentation: ZENKO-1357 Fix_PDF_Output
scality/Zenko pull request #488
Opened 2019-01-02 21:57 UTC by wabernatScality

This commit makes documentation build to PDF using the Scality
template for the latexpdf toolchain. This does not get us up to
production quality, but gets us much closer.

Remaining issues:
* Table formatting (ZENKO-1417)
* Project organization (This produces a good help website, searchable
  across all "books". The PDF contains all three "books" (inst, ops,
  and ref) as one hefty PDF. (ZENKO-1407)

Additionally, I modified the table in
Installation/topics/adding_NFS_storage.rst in anticipation of
ZENKO-1417.

2019-01-02 21:57 UTC, bert-e commented
# Hello wabernatscality,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get
information on this process.





*Status report is not available.*

2019-01-02 21:57 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZENKO-1357 contains:


* `Zenko 1.0.1`


Considering where you are trying to merge, I expected to find:


* `1.1.0`


Please check the `Fix Version/s` of ZENKO-1357, or the target
branch of this pull request.

2019-01-02 21:59 UTC, wabernatScality commented
@bert-e reset

2019-01-02 21:59 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2019-01-02 22:00 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @vrancurel

* @giacomoguiulfo

* @ssalaues

* @nicolast

2019-01-02 22:01 UTC, wabernatScality commented
@bert-e approve

2019-01-02 22:01 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @vrancurel

* @giacomoguiulfo

* @ssalaues

* @nicolast








*The following options are set:* **approve**

2019-01-03 19:33 UTC, ssalaues requested changes
Please delete all the `*.pyc` files that have been included. These are the compiled byte code files that shouldn't be part of the commit. Also would be a good idea to add `*.pyc` to the .gitignore file to prevent this in the future.

2019-01-03 22:06 UTC, wabernatScality commented
Made requested changes.

2019-01-03 22:07 UTC, ssalaues approved these changes

2019-01-07 18:45 UTC, jonathan-gramain approved these changes

2019-01-07 18:45 UTC, jonathan-gramain commented on docs/scaldoc/screenshot/__init__.py
> +Invert = Color.Invert_bgw
This seems to override the previous line

2019-01-07 18:45 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/1.1`



The following branches will **NOT** be impacted:

* `development/0.9`
* `development/1.0`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2019-01-07 19:27 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/1.1`



The following branches have **NOT** changed:

* `development/0.9`
* `development/1.0`



Please check the status of the associated issue ZENKO-1357.

Goodbye wabernatscality.

2019-01-07 19:27 UTC, merged