[squash] ZENKO-1420 create topic backbeat-data-mover
scality/Zenko pull request #512
Opened 2019-02-07 01:20 UTC by jonathan-gramain

**What does this PR do, and why do we need it?**

Create a new topic *backbeat-data-mover* to be consumed by the queue processor to provide data copy as a service, for use with transition policies first, then others in the future.

2019-02-07 01:21 UTC, bert-e commented
# Hello jonathan-gramain,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get
information on this process.





*Status report is not available.*

2019-02-07 01:21 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZENKO-1420 contains:


* *None*


Considering where you are trying to merge, I expected to find:


* `1.1.0`


Please check the `Fix Version/s` of ZENKO-1420, or the target
branch of this pull request.

2019-02-12 22:04 UTC, JianqinWang approved these changes

2019-02-12 22:08 UTC, alexanderchan-scality approved these changes

2019-02-12 22:28 UTC, giacope requested changes
This needs to be added to the `single-node-values.yaml` to maintain consistency.

2019-02-19 21:46 UTC, giacope approved these changes

2019-02-19 21:51 UTC, jonathan-gramain commented
@bert-e approve

2019-02-19 21:51 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZENKO-1420 contains:


* *None*


Considering where you are trying to merge, I expected to find:


* `1.1.0`


Please check the `Fix Version/s` of ZENKO-1420, or the target
branch of this pull request.




*The following options are set:* **approve**

2019-02-19 21:53 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @nicolast

* @vrancurel

* @ssalaues

* @giacomoguiulfo

2019-02-19 21:53 UTC, jonathan-gramain commented
@bert-e approve

2019-02-19 21:53 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/1.1`



The following branches will **NOT** be impacted:

* `development/0.9`
* `development/1.0`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2019-02-21 00:02 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/1.1`



The following branches have **NOT** changed:

* `development/0.9`
* `development/1.0`



Please check the status of the associated issue ZENKO-1420.

Goodbye jonathan-gramain.

2019-02-21 00:02 UTC, merged