ft: ZENKO-1238 E2E s3c ingestion tests
scality/Zenko pull request #591
Opened 2019-03-20 19:25 UTC by JianqinWang

- tests for ingestion and oob updates from RING S3C

ingestion tests on their own passed here:
https://eve.devsca.com/github/scality/zenko/#/builders/2/builds/2372

https://github.com/scality/Zenko/pull/590 reopened here

2019-03-20 19:25 UTC, bert-e commented
# Hello jianqinwang,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/zenko/bert-e/doc/user).





*Status report is not available.*

2019-03-20 19:25 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZENKO-1238 contains:


* *None*


Considering where you are trying to merge, I expected to find:


* `1.1.0`

* `1.2.0`


Please check the `Fix Version/s` of ZENKO-1238, or the target
branch of this pull request.

2019-03-20 19:27 UTC, JianqinWang commented
@bert-e reset

2019-03-20 19:27 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2019-03-20 19:27 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZENKO-1238 contains:


* `1.1.0`


Considering where you are trying to merge, I expected to find:


* `1.1.0`

* `1.2.0`


Please check the `Fix Version/s` of ZENKO-1238, or the target
branch of this pull request.

2019-03-20 20:32 UTC, JianqinWang commented
@bert-e reset

2019-03-20 20:32 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2019-03-20 20:32 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `feature/ZENKO-1238-ingestion-E2E-additional-tests` into
`development/1.1`
* [w/1.2/feature/ZENKO-1238-ingestion-E2E-additional-tests](https://github.com/scality/zenko/compare/development/1.2...w/1.2/feature/ZENKO-1238-ingestion-E2E-additional-tests) will be merged into `development/1.2` (pull request #592)



The following branches will **NOT** be impacted:

* `development/0.9`
* `development/1.0`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2019-03-20 20:32 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @giacomoguiulfo

* @ssalaues

* @nicolast

* @vrancurel

2019-03-20 22:49 UTC, bert-e commented
# History mismatch



Merge commit #8426f9f2a9e3c555f6cf593b2e515671c61062fd on the integration branch
`w/1.2/feature/ZENKO-1238-ingestion-E2E-additional-tests` is merging a branch which is neither the current
branch `feature/ZENKO-1238-ingestion-E2E-additional-tests` nor the development branch
`development/1.2`.

It is likely due to a rebase of the branch `feature/ZENKO-1238-ingestion-E2E-additional-tests` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2019-03-20 23:22 UTC, bert-e commented
# History mismatch



Merge commit #fa6f01210e53ec4cf9a05f17e08a68ed352cbe99 on the integration branch
`w/1.2/feature/ZENKO-1238-ingestion-E2E-additional-tests` is merging a branch which is neither the current
branch `feature/ZENKO-1238-ingestion-E2E-additional-tests` nor the development branch
`development/1.2`.

It is likely due to a rebase of the branch `feature/ZENKO-1238-ingestion-E2E-additional-tests` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2019-03-21 18:19 UTC, bert-e commented
# History mismatch



Merge commit #06b6c425a48fbacc01bfda8283b2d164a5699fde on the integration branch
`w/1.2/feature/ZENKO-1238-ingestion-E2E-additional-tests` is merging a branch which is neither the current
branch `feature/ZENKO-1238-ingestion-E2E-additional-tests` nor the development branch
`development/1.2`.

It is likely due to a rebase of the branch `feature/ZENKO-1238-ingestion-E2E-additional-tests` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2019-03-21 18:29 UTC, bert-e commented
# History mismatch



Merge commit #06b6c425a48fbacc01bfda8283b2d164a5699fde on the integration branch
`w/1.2/feature/ZENKO-1238-ingestion-E2E-additional-tests` is merging a branch which is neither the current
branch `feature/ZENKO-1238-ingestion-E2E-additional-tests` nor the development branch
`development/1.2`.

It is likely due to a rebase of the branch `feature/ZENKO-1238-ingestion-E2E-additional-tests` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2019-03-21 18:29 UTC, JianqinWang commented
@bert-e reset

2019-03-21 18:29 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2019-03-21 18:30 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `feature/ZENKO-1238-ingestion-E2E-additional-tests` into
`development/1.1`
* [w/1.2/feature/ZENKO-1238-ingestion-E2E-additional-tests](https://github.com/scality/zenko/compare/development/1.2...w/1.2/feature/ZENKO-1238-ingestion-E2E-additional-tests) will be merged into `development/1.2` (pull request #600)



The following branches will **NOT** be impacted:

* `development/0.9`
* `development/1.0`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2019-03-21 18:30 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @giacomoguiulfo

* @ssalaues

* @nicolast

* @vrancurel

2019-03-21 21:27 UTC, rahulreddy requested changes

2019-03-21 21:27 UTC, rahulreddy commented on tests/zenko_tests/node_tests/package.json
> +    "test_ingestion_s3c": "mocha --tags ${MOCHA_TAGS} --exit -t 60000 backbeat/tests/ingestion/ingestionS3C.js",
We don't need two commands for ingestion and oob, it can just be
```js
test_ingestion_s3c": "mocha --tags ${MOCHA_TAGS} --exit -t 60000 backbeat/tests/ingestion/"
```

This will run all the files under that directory, one at a time.

2019-03-21 21:27 UTC, rahulreddy commented on tests/zenko_tests/node_tests/backbeat/IngestionUtility.js
> +            next => this.s3.putBucketVersioning({
This is actually redundant as we automatically enable versioning on buckets with ingest location.

2019-03-21 21:27 UTC, rahulreddy commented on tests/zenko_tests/node_tests/backbeat/IngestionUtility.js
> +                objectExists = err === null;
`err` would be `undefined` no? Checking for falseness should be sufficient, `objectExists = !!err`

2019-03-21 21:27 UTC, rahulreddy commented on tests/zenko_tests/node_tests/backbeat/IngestionUtility.js
> +            this.s3.getObject({
`this.s3.headObject` should be sufficient and quicker.

2019-03-21 21:27 UTC, rahulreddy commented on tests/zenko_tests/node_tests/backbeat/IngestionUtility.js
> +                Key: key,
Don't we need a `versionId` to be specific?

2019-03-21 21:27 UTC, rahulreddy commented on tests/zenko_tests/node_tests/backbeat/IngestionUtility.js
> +            next => this.getSourceObject(srcBucket, key, next),
Same thing here, we are getting the master expecting for the versionId to be the same which is a test we should be doing. But we also need test comparing the versionied objects which you can follow up later.

2019-03-21 21:28 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @giacomoguiulfo

* @ssalaues

* @nicolast

* @vrancurel





The following reviewers are expecting changes from the author, or must review again:

* @rahulreddy

2019-03-21 21:34 UTC, JianqinWang commented on tests/zenko_tests/node_tests/package.json
> +    "test_ingestion_s3c": "mocha --tags ${MOCHA_TAGS} --exit -t 60000 backbeat/tests/ingestion/ingestionS3C.js",
omg I thought I fixed this, good catch thanks

2019-03-21 21:43 UTC, JianqinWang commented on tests/zenko_tests/node_tests/backbeat/IngestionUtility.js
> +                Key: key,
:sweat_smile: this function actually is not used, I will be removing it

2019-03-21 21:44 UTC, JianqinWang commented on tests/zenko_tests/node_tests/backbeat/IngestionUtility.js
> +                objectExists = err === null;
I think the `err` has been returned as `null`, same in ReplicationUtility - your way is much more thorough, thanks

2019-03-21 22:26 UTC, bert-e commented
# History mismatch



Merge commit #af092ec76ac376c716a2e9ca38651880e11c932a on the integration branch
`w/1.2/feature/ZENKO-1238-ingestion-E2E-additional-tests` is merging a branch which is neither the current
branch `feature/ZENKO-1238-ingestion-E2E-additional-tests` nor the development branch
`development/1.2`.

It is likely due to a rebase of the branch `feature/ZENKO-1238-ingestion-E2E-additional-tests` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2019-03-21 23:05 UTC, bert-e commented
# History mismatch



Merge commit #79853b64db2f5e048ad4514a080c70e65e4f814c on the integration branch
`w/1.2/feature/ZENKO-1238-ingestion-E2E-additional-tests` is merging a branch which is neither the current
branch `feature/ZENKO-1238-ingestion-E2E-additional-tests` nor the development branch
`development/1.2`.

It is likely due to a rebase of the branch `feature/ZENKO-1238-ingestion-E2E-additional-tests` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2019-03-21 23:39 UTC, bert-e commented
# History mismatch



Merge commit #79853b64db2f5e048ad4514a080c70e65e4f814c on the integration branch
`w/1.2/feature/ZENKO-1238-ingestion-E2E-additional-tests` is merging a branch which is neither the current
branch `feature/ZENKO-1238-ingestion-E2E-additional-tests` nor the development branch
`development/1.2`.

It is likely due to a rebase of the branch `feature/ZENKO-1238-ingestion-E2E-additional-tests` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2019-03-22 17:07 UTC, rahulreddy commented on tests/zenko_tests/node_tests/backbeat/IngestionUtility.js
> +                status = !err;
I think you have a typo here. It should be `status = !!err`

2019-03-22 19:11 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZENKO-1238 contains:


* `1.1.0`

* `1.2.0`


Considering where you are trying to merge, I expected to find:


* `1.1.0`


Please check the `Fix Version/s` of ZENKO-1238, or the target
branch of this pull request.

2019-03-22 19:21 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @giacomoguiulfo

* @ssalaues

* @nicolast

* @vrancurel





The following reviewers are expecting changes from the author, or must review again:

* @rahulreddy

2019-03-22 21:28 UTC, JianqinWang commented
https://eve.devsca.com/github/scality/zenko/#/builders/2/builds/2465 tests passed prior to squash

2019-03-22 22:13 UTC, rahulreddy approved these changes

2019-03-22 22:13 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @giacomoguiulfo

* @ssalaues

* @nicolast

* @vrancurel

2019-03-22 22:24 UTC, tmacro approved these changes

2019-03-22 22:26 UTC, ssalaues approved these changes

2019-03-22 22:26 UTC, JianqinWang commented
@bert-e approve

2019-03-22 23:01 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/Zenko/commit/6fd0a635a0b13a88320fb725d7e361b86b1c809f) did not succeed in branch feature/ZENKO-1238-ingestion-E2E-additional-tests.




*The following options are set:* **approve**

2019-03-25 17:28 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/Zenko/commit/7d23d24209f9d232945f8af6d4176af888268374) did not succeed in branch feature/ZENKO-1238-ingestion-E2E-additional-tests.




*The following options are set:* **approve**

2019-03-25 17:34 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/Zenko/commit/7d23d24209f9d232945f8af6d4176af888268374) did not succeed in branch feature/ZENKO-1238-ingestion-E2E-additional-tests.




*The following options are set:* **approve**

2019-03-25 17:34 UTC, JianqinWang commented
@bert-e reset

2019-03-25 17:34 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.






*The following options are set:* **approve**

2019-03-25 19:05 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/Zenko/commit/7d23d24209f9d232945f8af6d4176af888268374) did not succeed in branch feature/ZENKO-1238-ingestion-E2E-additional-tests.




*The following options are set:* **approve**

2019-03-25 21:13 UTC, rahulreddy commented
@bert-e bypass_build_status
Exceptionally merging as we are aware of a bug unrelated to this PR causing the tests to fail.

2019-03-25 21:13 UTC, bert-e commented
# Unknown command



I didn't understand this comment by @rahulreddy:

> @bert-e bypass_build_status
> Exceptionally merging as we are aware of a bug unrelated to this PR causing the tests to fail.

I don't know what `Exceptionally` means.

Please **edit** or **delete** the corresponding comment so I can move on.




*The following options are set:* **bypass_build_status, approve**

2019-03-25 21:14 UTC, rahulreddy commented
@bert-e bypass_build_status

2019-03-25 21:14 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/1.1`



The following branches will **NOT** be impacted:

* `development/0.9`
* `development/1.0`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **bypass_build_status, approve**

2019-03-26 04:54 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/1.1`



The following branches have **NOT** changed:

* `development/0.9`
* `development/1.0`



Please check the status of the associated issue ZENKO-1238.

Goodbye jianqinwang.

2019-03-26 04:54 UTC, merged