documentation: ZENKO-1751_clean_up_SMB/CIFS_dox
scality/Zenko pull request #653
Opened 2019-04-24 19:31 UTC by wabernatScality

This PR fixes, harmonizes, and reorders the configuration instructions for
CIFS/SMB and NFS features. You need it because it clarifies the instructions
and puts them in context (which are goods without qualification).

This PR fixes ZENKO-1751

2019-04-24 19:31 UTC, bert-e commented
# Hello wabernatscality,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/zenko/bert-e/doc/user).





*Status report is not available.*

2019-04-24 19:31 UTC, bert-e commented
# Conflict




There is a conflict between your branch `documentation/ZENKO-1751_clean_up_SMB/CIFS_dox` and the
destination branch `development/1.1`.

Please resolve the conflict on **the feature branch** (`documentation/ZENKO-1751_clean_up_SMB/CIFS_dox`).

```bash
 $ git fetch
 $ git checkout origin/documentation/ZENKO-1751_clean_up_SMB/CIFS_dox
 $ git merge origin/development/1.1
 $ # <intense conflict resolution>
 $ git commit
 $ git push origin HEAD:documentation/ZENKO-1751_clean_up_SMB/CIFS_dox
```

2019-04-24 19:50 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @tmacro

* @nicolast

* @ssalaues

* @vrancurel

2019-04-24 19:51 UTC, wabernatScality commented
@bert-e approve

2019-04-24 19:51 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @tmacro

* @nicolast

* @ssalaues

* @vrancurel










*The following options are set:* **approve**

2019-04-25 23:02 UTC, ssalaues requested changes
just a small detail otherwise lgtm

2019-04-25 23:02 UTC, ssalaues commented on docs/docsource/Installation/configure/adding_CIFS_storage.rst
> +#. Create a bucket in this location.
Should probably specify the `Mirroring Mode` bucket creation. It's not a really a huge issue now but in the future when we support writing files this distinction will become crucial.

2019-04-25 23:02 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @tmacro

* @nicolast

* @ssalaues

* @vrancurel





The following reviewers are expecting changes from the author, or must review again:

* @ssalaues







*The following options are set:* **approve**

2019-04-26 18:31 UTC, wabernatScality commented on docs/docsource/Installation/configure/adding_CIFS_storage.rst
> +#. Create a bucket in this location.
I don't have a working NFS instance to test against, so I don't understand what this means. 

Do you have an NFS server I can "walk the steps" with? If not, can you take a screengrab of this step?

2019-04-26 22:22 UTC, ssalaues approved these changes

2019-04-26 22:22 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @tmacro

* @nicolast

* @ssalaues

* @vrancurel










*The following options are set:* **approve**

2019-04-29 21:04 UTC, dora-korpar approved these changes

2019-04-29 21:04 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/1.1`



The following branches will **NOT** be impacted:

* `development/0.9`
* `development/1.0`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2019-04-29 21:11 UTC, tmacro approved these changes

2019-04-30 20:28 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/1.1`



The following branches have **NOT** changed:

* `development/0.9`
* `development/1.0`



Please check the status of the associated issue ZENKO-1751.

Goodbye wabernatscality.

2019-04-30 20:28 UTC, merged