ZENKO-2236 single truth sphinx build
scality/Zenko pull request #911
Opened 2019-11-25 22:10 UTC by tcarmet

In this PR we're removing duplicated `conf.py` sphinx file for documentation, keeping a single point of truth to build it.

2019-11-25 22:10 UTC, bert-e commented
# Hello tcarmet,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/zenko/bert-e/doc/user).





*Status report is not available.*

2019-11-25 22:10 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZENKO-2236 contains:


* `1.1.1`


Considering where you are trying to merge, I expected to find:


* `1.1.5`

* `1.2.0`


Please check the `Fix Version/s` of ZENKO-2236, or the target
branch of this pull request.

2019-11-25 23:14 UTC, wabernat approved these changes

2019-11-25 23:17 UTC, wabernat requested changes
Please remove the Makefile from the Reference book. This leaves docs/Makefile (which I think is about the make shell command) and docs/docsource/, which appears necessary.

2019-11-25 23:22 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZENKO-2236 contains:


* *None*


Considering where you are trying to merge, I expected to find:


* `1.1.5`

* `1.2.0`


Please check the `Fix Version/s` of ZENKO-2236, or the target
branch of this pull request.

2019-11-26 00:02 UTC, tcarmet commented
@wabernatScality done, thanks for the review :heart:

2019-11-26 00:02 UTC, tcarmet commented
/approve

2019-11-26 00:02 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `documentation/ZENKO-2236-single-truth-sphinx-build` into
`development/1.1`
* [w/1.2/documentation/ZENKO-2236-single-truth-sphinx-build](https://github.com/scality/zenko/compare/development/1.2...w/1.2/documentation/ZENKO-2236-single-truth-sphinx-build) will be merged into `development/1.2` (pull request #912)



The following branches will **NOT** be impacted:

* `development/0.9`
* `development/1.0`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2019-11-26 00:02 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @nicolast

* @ssalaues

* @tmacro

* @vrancurel





The following reviewers are expecting changes from the author, or must review again:

* @wabernatscality

2019-11-26 00:02 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @nicolast

* @ssalaues

* @tmacro

* @vrancurel





The following reviewers are expecting changes from the author, or must review again:

* @wabernatscality







*The following options are set:* **approve**

2019-11-26 00:07 UTC, tmacro approved these changes

2019-11-26 00:14 UTC, JianqinWang approved these changes

2019-11-26 16:53 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @tmacro

* @rahulreddy

* @vrancurel

* @nicolast





The following reviewers are expecting changes from the author, or must review again:

* @wabernatscality







*The following options are set:* **approve**

2019-11-26 16:55 UTC, wabernat approved these changes

2019-11-26 16:56 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/1.1`

* :heavy_check_mark: `development/1.2`



The following branches will **NOT** be impacted:

* `development/0.9`
* `development/1.0`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2019-11-26 16:56 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/1.1`

* :heavy_check_mark: `development/1.2`



The following branches have **NOT** changed:

* `development/0.9`
* `development/1.0`



Please check the status of the associated issue ZENKO-2236.

Goodbye tcarmet.

2019-11-26 16:56 UTC, merged